apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: backweb2-v1
  namespace: demo
  labels:
    app: backweb2
    version: v1
spec:
  replicas: 1
  selector:
    app: backweb2
    version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backweb2
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: backweb2-v1
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/backweb2:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Rolling
    rollingParams:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
