kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: cds
  
spec:
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    git:
      uri: https://github.com/fj-s-asai/rhocp-demo-cds.git
      ref: master
    type: Git
    
  output:
    to:
      kind: ImageStreamTag
      name: 'cds:1.0'
  triggers:
    - type: ConfigChange
