apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdsupdater
spec:
  selector:
    app: cdsupdater
  replicas: 1
  template:
    metadata:
      labels:
        app: cdsupdater
    spec:
      containers:
        - name: cdsupdater
          image: image-registry.openshift-image-registry.svc:5000/cds/cdsupdater:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/demo"
              name: "pvol"
      
      volumes:
        - name: "pvol"
          persistentVolumeClaim:
            claimName: pvc-cds-data-vol



