apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: cdsupdater
spec:
  selector:
    app: cdsupdater
  replicas: 1
  template:
    metadata:
      labels:
        app: cdsupdater
    spec:
      containers:
        - name: cdsupdater
          image: image-registry.openshift-image-registry.svc:5000/cds/cdsupdater:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/demo"
              name: "pvol" 
      volumes:
        - name: "pvol"
          persistentVolumeClaim: 
            claimName: pvc-cds-data-vol
  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        from:
          kind: "ImageStreamTag"
          name: "cdsupdater:1.0"
        containerNames:
          - "cdsupdater"
          