apiVersion: batch/v1
kind: Job
metadata:
  name: cdsupdater
spec:
  selector:
    app: cdsupdater
  template:
    metadata:
      labels:
        app: cdsupdater
    spec:
      containers:
        - name: cdsupdater
          image: image-registry.openshift-image-registry.svc:5000/cds/cdsupdater:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/demo"
              name: "pvol"
      volumes:
        - name: "pvol"
          persistentVolumeClaim: 
            claimName: pvc-cds-data-vol
      restartPolicy: Never
