apiVersion: v1
kind: PersistentVolume
metadata:
  name: cds-nfs-rwx-1g
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /tmp
    server: 10.40.5.121


