kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cds-data-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  
