apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
 name: "pipeline-finder"
spec:
  triggers:
    - github:
        secret: finder
      type: GitHub
  source:
    git:
      uri: "https://github.com/yuu-ymt/rhocp-demo-finder.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile