apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: image-registry.openshift-image-registry.svc:5000/cds/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

