kind: Service
apiVersion: v1
metadata:
  name: backweb1
  namespace: demo
  labels:
    app: backweb1
    service: backweb1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: frontweb
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
