kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mysql
spec:
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    git:
      uri: https://github.com/fj-s-asai/rhocp-demo-mysql.git
      ref: master
    type: Git
    
  output:
    to:
      kind: ImageStreamTag
      name: 'mysql:1.0'
  triggers:
    - type: ConfigChange
