apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: image-registry.openshift-image-registry.svc:5000/demo/mysql:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3306

