apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo-mysql
  nfs:
    path: /tmp
    server: 172.17.0.2
