kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql-data-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  
