kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: restdb
spec:
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    git:
      uri: https://github.com/yuu-ymt/rhocp-demo-restdb.git
      ref: master
    type: Git
    
  output:
    to:
      kind: ImageStreamTag
      name: 'restdb:1.0'
  triggers:
    - type: ConfigChange
