apiVersion: apps/v1
kind: Deployment
metadata:
  name: restdb-v10
  labels:
    app: restdb
    version: v10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restdb
      version: v10
  template:
    metadata:
      labels:
        app: restdb
        version: v10
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: restdb-v10
          image: image-registry.openshift-image-registry.svc:5000/demo/restdb:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always


