apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: restdb
spec:
  selector:
    app: restdb
  replicas: 1
  template:
    metadata:
      labels:
        app: restdb
    spec:
      containers:
        - name: restdb
          image: image-registry.openshift-image-registry.svc:5000/demo/restdb:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        from:
          kind: "ImageStreamTag"
          name: "restdb:1.0"
        containerNames:
          - "restdb"
