apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
 name: "pipeline-frontweb-v11"
spec:
  triggers:
    - github:
        secret: frontweb11
      type: GitHub
  source:
    git:
      uri: "https://github.com/fj-s-asai/rhocp-demo-frontweb.git"
      ref: v11
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
