apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: frontweb
spec:
  selector:
    app: frontweb
  replicas: 1
  template:
    metadata:
      labels:
        app: frontweb
    spec:
      containers:
        - name: frontweb
          image: image-registry.openshift-image-registry.svc:5000/demo/frontweb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080