apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontweb-v1
  namespace: demo
  labels:
    app: frontweb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: frontweb
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontweb
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: frontweb-v1
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/frontweb:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

