apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontweb-1.0
  labels:
    app: frontweb
    version: 1.0
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: frontweb
      version: 1.0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontweb
        version: 1.0
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: frontweb-1.0
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/frontweb:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always


